<?php
/**
 *   Copyright (c) 2016, Peter Johnson
 *   All rights reserved.
 *
 *   Redistribution and use in source and binary forms, with or without
 *   modification, are permitted provided that the following conditions are met:
 *
 *    * Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 *
 *    * Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 *    * Neither the name of [project] nor the names of its
 *   contributors may be used to endorse or promote products derived from
 *   this software without specific prior written permission.
 *
 *   THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 *   AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 *   IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 *   DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 *   FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 *   DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 *   SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 *   CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 *   OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 *   OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/**
 * @file
 * Display PDF files using PDF.js
 */

/**
 * Implementation of hook_menu().
 */
function reader_menu() {
  $items = array();
  $items['reader/%node'] = array(
    'title' => t('View Document'),
    'page callback' => 'reader_view',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK
  );
  return $items;
}

/**
 * View a PDF
 */
function reader_view($node) {
  node_build_content($node);
  $output = 'This shouldn\'t happen';
  foreach ($node->content as $field) {
    if ($field['#formatter'] == 'reader_link') {
      $entity = entity_load($field['#entity_type'], array($node->nid));
      return field_view_field($field['#entity_type'], $entity[1], $field['#field_name'], array('type' => 'reader'));
    }
  }
  return $output;
}

/**
 * Implementation of CCK's hook_field_formatter_info().
 */
function reader_field_formatter_info() {
  return array(
    'reader' => array(
      'label' => t('reader: HTML5 PDF reader'),
      'field types' => array('file', 'uploadfield', 'link'),
    ),
    'reader_link' => array(
      'label' => t('reader_link: Link to HTML5 PDF reader'),
      'field types' => array('file', 'uploadfield', 'link'),
    )
  );
}

/**
 * Implementation of hook_theme().
 */
function reader_theme() {
  return array(
    'reader' => array(
      'variables' => array('html' => array()),
      'path' => drupal_get_path('module', 'reader'),
      'template' => 'reader',
    ),
  );
}

/**
 * Implementation of hook_field_formatter_view().
 */
function reader_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();

  foreach ($items as $delta => $item) {
    switch ($display['type']) {
      case 'reader':
        drupal_set_title($entity->title.' | '.$item['filename']);
        break;
      case 'reader_link':
        $element[$delta] = array(
          '#markup' => '<div class="reader-link"><div class="reader-link-title">'.$entity->title.'</div>'
            .l(t('View'), 'reader/'.$entity->nid, array('attributes'=>array('class'=>array('reader-beta')))).' | '.l(t('Download'), file_create_url($item['uri']))
        );
        break;
    }
  }
  return $element;
}

function reader_theme_registry_alter(&$theme_registry) {
  $theme_hook = 'html'; // my hook name
  // Get the path to this module
  $modulepath = drupal_get_path('module', 'reader');
  $theme_registry += drupal_find_theme_templates($theme_registry, '.tpl.php', $modulepath);
  // Add the module path on top in the array of paths
  //unset($theme_registry[$theme_hook]['theme paths'], $modulepath);
  // dsm($theme_registry[$theme_hook]['theme paths']);
}